#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

$HOME/.fehbg

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi


# Merge in defaults and keymaps
[ -f $sysresources ] && /usr/bin/xrdb -merge $sysresources
[ -f $sysmodmap ] && /usr/bin/xmodmap $sysmodmap
[ -f $userresources ] && /usr/bin/xrdb -merge $userresources
[ -f $usermodmap ] && /usr/bin/xmodmap $usermodmap

# agents
eval `ssh-agent`
eval `gpg-agent --daemon`

#misc vars
export QT_QPA_PLATFORMTHEME='qt5ct'
export TERMINAL='/usr/bin/st'
export BROWSER='/usr/bin/firefox'
#misc stuff, mostly housekeeping
xset -b
start-pulseaudio-x11
#xscreensaver -no-splash
